name: Build Zed

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_HOME: ${{ github.workspace }}/.cargo-home
  RUSTUP_HOME: ${{ github.workspace }}/.rustup

jobs:
  build:
    runs-on: depot-ubuntu-latest-8
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install system dependencies
      run: |
        ./script/linux
        # Install mold if not already present
        if ! command -v mold >/dev/null 2>&1; then
          sudo apt-get update
          sudo apt-get install -y mold
        fi

    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
        echo "${{ github.workspace }}/.cargo-home/bin" >> $GITHUB_PATH

    - name: Setup Rust toolchain
      run: |
        rustup show
        rustc --version
        cargo --version

    - name: Run tests
      continue-on-error: true
      env:
        RUSTFLAGS: "-C link-arg=-fuse-ld=mold"
      run: |
        cargo test --workspace --lib --tests --no-fail-fast

    - name: Build Zed (release)
      run: |
        cargo build --release